apiVersion: v2
name: sabnzbdvpn
description: SABnzbd is an Open Source Binary Newsreader written in Python.
appVersion: "4.5.3"
type: application
version: 0.6.5
keywords:
  - sabnzbd
  - vpn
  - music
  - pvr
  - mediafactory
  - torrent
  - usenet
maintainers:
  - name: GenericEric
    email: eric@bgeneric.net
    url: https://bgeneric.net
